### ISSUE TITLE
Feature Points finalisation

### ISSUE THREAD

**Issue by andrewbutterfield** [tom-and-the-toothfairies/pathways#1]
Your average bids per feature are in the attached CSV file  (with a .txt extension).

Revise as you see fit and use this issue tracker for clarification regarding the features
[Opening5.txt](https://github.com/tom-and-the-toothfairies/pathways/files/751156/Opening5.txt)

**Comment by 22a** [comment]
[toothbids-group5.pdf](https://github.com/tom-and-the-toothfairies/pathways/files/760507/tom.2thfairy.-.Sheet1.pdf)
Here are our revised bids for your viewing pleasure

**Comment by shawa** [comment]
|Feature|Points Estimate
| :- | -:
|PML File Selection|3
|PML File Loading|3
|PML Analysis Selection|13
|Running PML Analysis|15
|On-Screen PML Reporting|13
|PML Log-file Generation|14
|PML Error and Warning highlights|15
|Select specific OWL Ontology|3
|Load Selected Ontology|12
|Identify drugs in PML|20
|Identify drugs in DINTO|20
|Identify DDIs|25
|On-Screen DINTO Reporting|15
|DINTO Logfile Generation|14
|DINTO Error and Warning highlights|14
|Adding Time to PML|78
|DDI Timing Analysis|80
|Merging Clinical Pathways written in PML|30
|DDI-aware Pathway modifications|60
|Subsetting DINTO|120
|DINTO re-structuring|160
|finfer-friendly PEOS|30
|fbinfer-proof PEOS|30

**Total points**: 787

**Comment by andrewbutterfield** [comment]
Here are your features. 
[R1-G5-Points.xlsx](https://github.com/tom-and-the-toothfairies/pathways/files/770794/R1-G5-Points.xlsx)
