### ISSUE TITLE
[Panacea] custom pipeline for `/api` requests

### ISSUE THREAD

**Issue by c-brenn** [tom-and-the-toothfairies/pathways#100]
At the moment we're using the browser pipeline for API requests - which means that phoenix is doing a bunch of unnecessary work on each request. It also means that post requests need CSRF tokens.

A minimal custom pipeline would probably be better - one that just accepts json and does some basic `Phoenix.Token` access control.

**Comment by 22a** [comment]
I don't know how to do this `Phoenix.Token` stuff but I support the change nonetheless!
