### ISSUE TITLE
Drugs should be represented within PML by their English Labels

### ISSUE THREAD

**Issue by shawa** [tom-and-the-toothfairies/pathways#102]
At the moment if a clinician wants to represent a drug in their PML file they must use `dinto:db123` or `chebi:124` which, as raised in the meeting, is not very friendly. There'll be two changes required to accommodate this

# Representation in PML 

After some investigation, every Drug URI in DINTO has a corresponding english label, as seen when calling Asclepius' `/all_drugs` endpoint:

```
[
  {
    "label": "6-propyl-2-thiouracil",
    "uri": "http://purl.obolibrary.org/obo/CHEBI_8502"
  },
  {
    "label": "drospirenone",
    "uri": "http://purl.obolibrary.org/obo/CHEBI_50838"
  },
  {
    "label": "mefenamic acid",
    "uri": "http://purl.obolibrary.org/obo/DINTO_DB00784"
  },
  {
    "label": "dicloxacillin",
    "uri": "http://purl.obolibrary.org/obo/CHEBI_4511"
  },
  {
    "label": "amprenavir",
    "uri": "http://purl.obolibrary.org/obo/CHEBI_40050"
  },
  {
    "label": "norethisterone",
    "uri": "http://purl.obolibrary.org/obo/CHEBI_7627"
  },
  {
    "label": "avanafil",
    "uri": "http://purl.obolibrary.org/obo/CHEBI_66876"
  }
]
```

A simple way to allow these representations would be to add a `drugs` block to the requires block in a PML, at the moment we have:

```
process foo {
  task bar {
    action baz {
      tool { "pills" }
      script { "eat the pills" }
      agent { "patient" }
      requires { quux, "chebi:66876", "dinto:DB00784" }
      provides { "a cured patient" }
    }
  }
}
```

Which would be replaced by:

```
process foo {
  task bar {
    action baz {
      tool { "pills" }
      script { "eat the pills" }
      agent { "patient" }
      requires { quux, drugs {"avanafil", "mefenamic acid"} }
      provides { "a cured patient" }
    }
  }
}
```

Other suggestions are: 
* plain strings with a prefix`"drug:mefenamic acid"`, 
* python-style prefixed strings: `d"mefenamic acid"`
* special quotes: `<<mefenamic acid>>`

# Querying DINTO
As far as DINTO queries go, the simplest solution that comes to mind is:

1. On startup, Panacea calls `/all_drugs` and and builds a `label -> uri` hash.
2. After parsing the PML file, resolves parsed drug labels to URIs
  - At this point we can highlight labels that don't exist
3. Truncate the URIs to generate the corresponding `dinto:db123/chebi:123` identifiers to send to Asclepius

The DDIs come back with drug URIs and a DDI label. This creeps into the other issue of how to display the DDIs in the file, and is outside the scope of this issue.

**Comment by 22a** [comment]
Nice investigation, @shawa ! +2

**Comment by c-brenn** [comment]
@shawa is in the process of adding a new endpoint to asclepius that will turn english identfiers into dinto URIs. 

With the parser changes in #106 we can then allow users to use english in PML but continue to use URIs in the backend.

This new endpoint will probably mean adding a step to #88. 

User uploads file - frontend gets the list of english drugs in the document. The frontend then asks for the uris for these drugs and gets back uris and the list of drugs that could not be resolved to uris. The frontend then asks for the ddis between the resolved uris.

**Comment by 22a** [comment]
When you say `User uploads file - frontend gets the list the list of english drugs in the document.` do you mean that the js does the parsing for english drug names then sends off to panacea or that it sends the file to panacea and gets names back?

**Comment by c-brenn** [comment]
Panacea sends them back. Instead of sending back `["chebi:...", "dinto:..."]` like it currently does, it'll send back the exact english that appears in the document - `["paracetamol", "flat seven up"]`.

These then have to be resolved into `chebi:...` identifiers - using the new endpoint. This allows us to report to the user about "drugs" that we could not identify.
