### ISSUE TITLE
When a new file is chosen, the page should update the current analysis

### ISSUE THREAD

**Issue by ajenner** [tom-and-the-toothfairies/pathways#103]
Currently the page only updates when a new file is submitted which contains drugs or invalid pml. If an empty file is submitted then no update of the page occurs.
When a new file is selected, the page should reset back to a clean slate and wipe all previously displayed analysis. This should happen when the file is selected not just when it is submitted.

**Comment by ajenner** [comment]
#98 deals with the empty file issue. This issue now purely deals with changing the update time.

**Comment by 22a** [comment]
There is a super quick fix to this, merely call the [`hideResults` function](https://github.com/tom-and-the-toothfairies/pathways/blob/release-1/panacea/web/static/js/app.js#L37-L40) inside [the file input's on changed event handler](https://github.com/tom-and-the-toothfairies/pathways/blob/release-1/panacea/web/static/js/app.js#L78-L80).

You're correct @ajenner, the controller error that causes the old results to stay there after a bad file is analysed is the concern of https://github.com/tom-and-the-toothfairies/pathways/issues/98 and by extension https://github.com/tom-and-the-toothfairies/pathways/issues/88

**Comment by c-brenn** [comment]
closed by #105 but leaving this open for now because it needs to be documented in the change log

**Comment by 22a** [comment]
messed that up, just meant to unassign and reassign @ajenner :six:
