### ISSUE TITLE
UI updates

### ISSUE THREAD

**Issue by c-brenn** [tom-and-the-toothfairies/pathways#108]
#107 - now that we have a chain of requests we can make some changes to the UI.

Opening this so we can discuss what these changes should entail.

**Comment by c-brenn** [comment]
From @22a's comment on #107 :

* what do we want to display to the user when the request chain is broken at the different points (when found URI's is less than 2 and when identifiable drugs is less than 0{thinking about this, this should also probably be 2, as there's no point getting the uri of one drug alone})

* do we want to make the error panel more expressive (where we can change the panel header as well)

**Comment by c-brenn** [comment]
#89 is probably relevant to this

**Comment by 22a** [comment]
yes v relevant, will be able to write helper functions that render real html elements in the result panels instead of overwriting `.innerHTML`, should be 🍑y

**Comment by c-brenn** [comment]
Improving the error messages that panacea sends back would probably go a long way in helping the UI show nice error messages.

Instead of just getting back `{message: "..."}` it should probably return some JSON with the type of error and some useful bits - line number for pml errors for example. The JS can construct whatever error message it likes from that info instead of having to pass along the hardcoded one from panacea.

**Comment by 22a** [comment]
as mentioned in slack, swapping [these two lines](https://github.com/tom-and-the-toothfairies/pathways/blob/release-1/panacea/web/static/js/app.js#L31-L32) would be a temporary solution to display when no drugs are found. Long term we probably want an error type message instead of a green-success box with an empty list literal

**Comment by laurmurclar** [comment]
For the moment I'm just going to test that no panels are shown when there's no drugs.

**Comment by 22a** [comment]
@laurmurclar well i suppose at least some feed back should be given to the user that there was no parseable drugs in the pml file they uploaded

**Comment by laurmurclar** [comment]
Oh yeah absolutely, but I don't want to mix that change in with the test stuff. I can add a no drugs message now

**Comment by 22a** [comment]
Oh okay sorry yes ofc! 🙏

**Comment by c-brenn** [comment]
there was some more discussion on slack today. The broad idea that came from it was:

- display the found drugs from the `/api/uris` response in the drugs panel, not the labels from `/api/pml`
- if possible, the found drugs should link to some chemistry/medical website (e.g. `https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:15377` <- takes a chebi id
-  if there are any `unidentified drugs` show the PML file contents and highlight them
- if there are any `DDIs`, show the PML file contents and highlight them

**Comment by c-brenn** [comment]
a distant memory
