### ISSUE TITLE
Drag and Drop file selection

### ISSUE THREAD

**Issue by ajenner** [tom-and-the-toothfairies/pathways#130]
The user should be able to drag and drop files into their browser. This would either upload them automatically or simply select the files for upload via the submit button.

**Comment by 22a** [comment]
bleugh https://github.com/tom-and-the-toothfairies/pathways/tree/22a/dragon

**Comment by c-brenn** [comment]
Is this still a feature we're trying to implement @22a @ajenner?

The customer didn't purchase `merging pathways` so multiple files aren't  a concern anymore

**Comment by 22a** [comment]
Well if thats the case it should be trivial (30 mins work) to have the entire page be a dropzone that automatically triggers the request chain, could possibly blow some minds, ethics committees would be ECSTATIC! thoughts @ajenner ?

**Comment by 22a** [comment]
That being said, it's not part of the desired feature set and could cause more confusion than it's worth given **the customer already likes the file selection medium very much**. Perhaps it would be pertinent to focus our dev efforts on non-stretch goals at the moment.

**Comment by ajenner** [comment]
Im not really sure this is worth doing anymore. I had some issues getting it to work and overall I think we should focus on things we're being directly marked on.

**Comment by 22a** [comment]
Looks like this is settled, drag and drop file selection was a stretch goal that we will not be stretching to.
