### ISSUE TITLE
Relase 2 Feature Estimation

### ISSUE THREAD

**Issue by shawa** [tom-and-the-toothfairies/pathways#139]
Notwithstanding the questions surrounding DINTO and timing, we should fill out the preliminary estimation form on [Google Sheets](https://docs.google.com/spreadsheets/d/1xmomEi5TekxSlt4fA79-Pf8MWitwGJ-3SOwmzwfvtKE/edit#gid=1570203487)

There is random data in there at the moment, with dainty statistical analysis ready to go.

**Comment by 22a** [comment]
https://github.com/andrewbutterfield/CS4098-2017/blob/master/Release-2-Bidding.csv

**Comment by c-brenn** [comment]
Added the new features and reordered everything to be the same as the csv.

Left out the amortised costs - I guess we can figure that out after we have our actual estimates?

**Comment by c-brenn** [comment]
@andrewbutterfield Attached are our bids for release 2. I will comment below with a table for convenience too.
[Group-5-Release-2-Bidding.xlsx](https://github.com/tom-and-the-toothfairies/pathways/files/853103/Group-5-Release-2-Bidding.xlsx)

**Comment by c-brenn** [comment]
|**Urgent**|	**Feature**|	**Cost**		| | |
|---|---|---|---|---|
|u|	Mock DDI Characterisation Data	 | 20 |		 | |
| | Identify drugs in PML	 | 0 |		 | |
| | Lookup drugs in DINTO	 | 0 |		 | |
| | Faster DINTO Loading	 | 5 |		 | |
| | Identify DDIs	 | 0 |		 | |
|u|	Report un-named PML construct	 | 15 |		 | |
|u|	Report PML construct name-clash	 | 20 |		 | |
| | Report use of task construct	 | 8 |		 | |
| | Identify Sequential DDIs	 | 20 |		 | |
| | Identify Parallel DDIs	 | 20 |		 | |
| | Report Alternative non-DDIs	 | 30 |		 | |
| | Report Repeated Alternative DDIs	 | 33 |		 | |
| | Specifying Periodic Drug Use	 | 38 |		 | |
| | Specifying Sequential Drug Use Gap	 | 50 |		 | |
| | Specifying Parallel Drug Use Gap	 | 50 |		 | |
| | Specifying Repeated Alternative Drug Use Gap	 | 50 |		 | |
| | Specify a Delay	 | 30 |		 | |
| | Specify a time interval offset	 | 35 |		 | |
| | Report Timing Inconsistencies	 | 120 |		 | |
| | Handle Timed Self-Interactions	 | 135 |		 | |
| | Identify DDI Closest Approach	 | 60 |		 | |
| | Identify DDI Furthest Separation	 | 60 |		 | |
| | Merging Clinical Pathways written in PML	 | 33 |		 | |
|u|	PML-TX Save PML to File	 | 15 |		 | |
| | Pathway Badness Ranking	 | 180 |		 | |
| | PML-TX Gradient Descent Time Optimisation | 200 |		 | |
| | PML-TX Brute Force Time Optimisation | 200 |		 | |
| | 			| | | | | |
| | PML-TX Rule-Based Transformation |	 190 |		 | |
| |   | | | |
| | 	| **Independent** |	**Amortized**	| **Rule  Based** |
| | PML-TX Reorder Sequence	 | 120 |	 50 |	 20 |
| | PML-TX Serialise Branch (Naive)	 | 105 |	 7 |	 20 |
| | PML-TX Serialize Branch (Two-Way)	 | 105 |	 7 |	 20 |
| | PML-TX Serialize Branch (Three-Way)	 | 110 |	 7 |	 20 |
| | PML-TX Serialize Branch (n-Way)	 | 115 |	 75 |	 30 |
| | PML-TX Remove Selections	 | 135 |	 60 |	 20 |
| | PML-TX Unroll Iteration	 | 123 |	 60 |	 25 |
| | PML-TX Parallelise Sequence	 | 123 |	 50 |	 25 |
| | **Total** | **2553** |	 **1933** |	 **1797** |

**Comment by andrewbutterfield** [comment]
Here is the bid spreadsheet as of the end of our meeting today - please revise bids or not, as you see fit, and then let me know...

[G5-Release-2-Backlog.xlsx](https://github.com/tom-and-the-toothfairies/pathways/files/862408/G5-Release-2-Backlog.xlsx)

**Comment by andrewbutterfield** [comment]
Have you decided if you are happy with your estimates?

**Comment by houli** [comment]
Hi @andrewbutterfield,

I've attached the updates to our estimates.
We’ve updated the estimates for the new features we talked about yesterday, would be quite interesting to see where we could take them.
[G5-Release-2-Backlog.xlsx](https://github.com/tom-and-the-toothfairies/pathways/files/864306/G5-Release-2-Backlog.xlsx)

**Comment by andrewbutterfield** [comment]
You've got them ! A
[G5-Release-2-Backlog.xlsx](https://github.com/tom-and-the-toothfairies/pathways/files/864377/G5-Release-2-Backlog.xlsx)
ny last comments?

**Comment by houli** [comment]
Good to go!

**Comment by andrewbutterfield** [comment]
OK - can you close this issue - I can't
