### ISSUE TITLE
PML-TX Save PML to File

### ISSUE THREAD

**Issue by houli** [tom-and-the-toothfairies/pathways#143]
Just need to provide a way to download what they've already uploaded...

**Comment by ajenner** [comment]
Do we want to simply store the uploaded files in memory until they're finished with them? (what are we doing with those files currently?) If so then this just requires adding a 'download' button somewhere on the screen.

**Comment by houli** [comment]
Yeah we'll probably need a way to associate uploads with a user, perhaps with the access token to keep them for downloading. Could be a genserver with a map or ets table.

Can do expiry by sending a message to itself `Process.send_after(self, {:expire, token}, seconds * 1000)` and handling that by doing map delete or w/e

**Comment by 22a** [comment]
Do we want these files to be persistent across multiple sessions? I saw this as being a simple in-memory store of the file which could all be handled in js without having to be the server's concern at all.

**Comment by c-brenn** [comment]
I thought an easy solution would be to send the AST to the front-end. Each transformation request sends the current AST in the request. We then return the new AST.

We have a function from PML to AST, once we have one that's AST to PML then this approach should work. No need to store any state server side

**Comment by 22a** [comment]
> Just need to provide a way to download what they've already uploaded...

has been implemented in https://github.com/tom-and-the-toothfairies/pathways/pull/145
