### ISSUE TITLE
Release 1 Feedback

### ISSUE THREAD

**Issue by andrewbutterfield** [tom-and-the-toothfairies/pathways#152]
As your repo is public I am emailing the feedback to you.

**Comment by c-brenn** [comment]
@andrewbutterfield There are some points of the feedback that we wish to discuss as part of our weekly meeting. 

Attached is a proposed agenda for our meeting tomorrow that outlines our areas of concern.
[AgendaItems.pdf](https://github.com/tom-and-the-toothfairies/pathways/files/858998/AgendaItems.pdf)
