### ISSUE TITLE
Specify a Delay

### ISSUE THREAD

**Issue by laurmurclar** [tom-and-the-toothfairies/pathways#154]

**Comment by laurmurclar** [comment]
So the easiest way I see to do this is to have an action `provide` a delay, which could be specified similarly to how we included drugs.

**Comment by c-brenn** [comment]
I think this is a good, simple approach.

What do you think about using `requires` instead of `provides`? i.e. `time` is a resource that any action can consume.

**Comment by laurmurclar** [comment]
Yeah, that works too. Whichever you think is better semantically - I think you're probably right in treating `time` as the resource rather than the `delay`.

**Comment by c-brenn** [comment]
I guess the next question is how we represent `time`. Not sure what's best here, what are you thinking @laurmurclar ?

I think @shawa did some investigation for the 'mock timing' feature. Did you find anything standard we could use?

**Comment by laurmurclar** [comment]
From the slack conversation:

```
time {
   days { 4 }
   hours { 3 }
   minutes { 2}
}
```
