### ISSUE TITLE
Identify Sequential DDIs

### ISSUE THREAD

**Issue by laurmurclar** [tom-and-the-toothfairies/pathways#156]

**Comment by c-brenn** [comment]
From the product backlog:

> A sequential DDI is one that arises because the PML contains a workflow in which the dispensing of one drug is always followed afterwards by the dispensing of another drug, that has an known interaction with the first. This feature should identify the drugs involved and the name of the smallest enclosing PML sequence construct

**Comment by c-brenn** [comment]
Panacea returns the DDI category now. This is UI changes from here.
