### ISSUE TITLE
Release 2 UI

### ISSUE THREAD

**Issue by c-brenn** [tom-and-the-toothfairies/pathways#162]
A place for discussing the UI for release 2.

Lots more information to display.

**Comment by c-brenn** [comment]
#164 adds more information about each DDI returned from `/api/ddis` - we'll need to figure out how best to display this

**Comment by 22a** [comment]
Perhaps we could incorporate some kind of [accordion](https://getbootstrap.com/javascript/#collapse-example-accordion) for each of the panels, perhaps with a faded preview of the top of the panel contents, when clicked it expands the panel fully.

**Comment by 22a** [comment]
After discussing the possibilities with our client we decided that https://github.com/tom-and-the-toothfairies/pathways/issues/177 was how we wanted to go forward for the Release 2 UI. This has been implemented in https://github.com/tom-and-the-toothfairies/pathways/pull/181.
