### ISSUE TITLE
Tabbed UI

### ISSUE THREAD

**Issue by houli** [tom-and-the-toothfairies/pathways#177]
Maybe like this
<img width="777" alt="screen shot 2017-03-29 at 15 47 38" src="https://cloud.githubusercontent.com/assets/143868/24460721/0e815874-1497-11e7-9cfa-f3063297d699.png">

**Comment by 22a** [comment]
https://github.com/tom-and-the-toothfairies/pathways/pull/181 implements this
![screenshot](https://cloud.githubusercontent.com/assets/7144173/24575047/2e1575e0-1694-11e7-90fa-e955cd8e15e6.png)
