### ISSUE TITLE
PML Elixir Parser

### ISSUE THREAD

**Issue by houli** [tom-and-the-toothfairies/pathways#25]
Just some possibly useful links https://github.com/bitwalker/combine (distillery author) https://github.com/alexrp/ex_parsec https://github.com/h4cc/awesome-elixir#lexical-analysis  https://github.com/marcelog/ex_abnf (might be able to take Andrew's BNFC and convert it to ABNF?)

**Comment by 22a** [comment]
thank you master houlihan 👍
