### ISSUE TITLE
Badges don't link to CI page

### ISSUE THREAD

**Issue by shawa** [tom-and-the-toothfairies/pathways#37]
@houli didn't properly review the README commit, the badge does not link to the CI page, this should be remedied with a link to the CI dashboard

**Comment by houli** [comment]
I am still working on this rest assured

**Comment by c-brenn** [comment]
another one ticked off the list. Great work team ! 💯 🥇 👴 👵

**Comment by 22a** [comment]
replying to the email to see what it does 🤡
