### ISSUE TITLE
Panacea should ask Asclepius about DDI's

### ISSUE THREAD

**Issue by c-brenn** [tom-and-the-toothfairies/pathways#46]

**Comment by 22a** [comment]
https://github.com/tom-and-the-toothfairies/pathways/pull/29/commits/d913974e114b52912e939ab1295eba820400fadc closed this, @c-brenn ? If so I'll make another to add the necessary bits to the view + js to view ddi's in the UI

**Comment by c-brenn** [comment]
The ability to ask is there but no asking occurs yet

**Comment by 22a** [comment]
This is being worked on here: https://github.com/tom-and-the-toothfairies/pathways/tree/identify_ddis
