### ISSUE TITLE
CI failures are successful

### ISSUE THREAD

**Issue by c-brenn** [tom-and-the-toothfairies/pathways#54]

**Comment by 22a** [comment]
yes they are, this should not be the case
<img width="369" alt="screen shot 2017-02-21 at 18 35 20" src="https://cloud.githubusercontent.com/assets/7144173/23179594/587b3a64-f866-11e6-9f08-e7e78c4dc320.png">

**Comment by houli** [comment]
Let me think about this one @22a

**Comment by c-brenn** [comment]
closed by 134b0519e49a675281c9d98d6d4d2c00bc122401
