### ISSUE TITLE
Consider something faster than RDFLib

### ISSUE THREAD

**Issue by shawa** [tom-and-the-toothfairies/pathways#55]
RDFLib is really really slow. Redland's librdf is supposedly faster, according to [this guy on stackoverflow](http://stackoverflow.com/questions/5678623/how-to-parse-big-datasets-using-rdflib)

We should try using librdf in the Dinto module and see if it's worth anything.

**Comment by houli** [comment]
https://wiki.python.org/moin/RdfLibraries

**Comment by shawa** [comment]
#77

**Comment by c-brenn** [comment]
🚤
