### ISSUE TITLE
JS fetch and formatting

### ISSUE THREAD

**Issue by houli** [tom-and-the-toothfairies/pathways#64]
Might be easier to use the `fetch` api here https://github.com/tom-and-the-toothfairies/pathways/blob/iteration-2/panacea/web/static/js/app.js#L24 rather than XHR, also formatting and semicolons and the like maybe even some async/await

**Comment by 22a** [comment]
staged for iteration 2: https://github.com/tom-and-the-toothfairies/pathways/pull/29/commits/f15a44623738d95ccc00d3611c5a30010f110f50
