### ISSUE TITLE
Conflicting drugs in asclepius response

### ISSUE THREAD

**Issue by houli** [tom-and-the-toothfairies/pathways#84]
```json
{
  "label": "abacavir/ganciclovir DDI",
  "uri": "http://purl.obolibrary.org/obo/DINTO_05759",
  "drug_a": "dinto_db123123",
  "drug_b": "chebi_1234124112"
}
```
or something like that so that the frontend can explain the cause of such a DDI

**Comment by shawa** [comment]
Only a minor modification to the sparql needed to put this in.

I'm wondering about `chebi_1234124112` we want to deviate from `chebi:1234124112`?
ATM it returns the full URI, but that can be transformed to w/e we need before serving it back to Panacea.

https://github.com/tom-and-the-toothfairies/pathways/commit/fcfbecbc1a26f71691f5b81d7247512250ab4b53

On a side note, it seems to be slowing down the test query we've been working against:

```
› time curl localhost:5000/ddis -X POST -d '{"drugs": ["chebi:421707", "chebi:465284", "dinto:DB00503", "chebi:9341"]}'
[
  {
    "drug_a": "http://purl.obolibrary.org/obo/CHEBI_421707",
    "drug_b": "http://purl.obolibrary.org/obo/CHEBI_465284",
    "label": "abacavir/ganciclovir DDI",
    "uri": "http://purl.obolibrary.org/obo/DINTO_05759"
  },
  {
    "drug_a": "http://purl.obolibrary.org/obo/CHEBI_421707",
    "drug_b": "http://purl.obolibrary.org/obo/DINTO_DB00503",
    "label": "abacavir/ritonavir DDI",
    "uri": "http://purl.obolibrary.org/obo/DINTO_11043"
  }
]
curl localhost:5000/ddis -X POST -d  -H 'Content-Type: application/json'  0.01s user 0.01s system 0% cpu 8.897 total
```

**Comment by houli** [comment]
Oh I just threw together those identifiers, instead of returning the uri of a and b I think just giving back `chebi:123` etc. as the cause is what we should do

**Comment by shawa** [comment]
https://github.com/tom-and-the-toothfairies/pathways/pull/85
