### ISSUE TITLE
PML controller should not be querying asclepius for ddi's

### ISSUE THREAD

**Issue by c-brenn** [tom-and-the-toothfairies/pathways#88]
PMLController probably should't be doing anything related to DDIs. 

This should be two requests in my opinion.

The file should be parsed and the drugs returned to the front-end. Depending on the number of drugs found (and perhaps user input), the front-end should then send a request for DDIs to a different endpoint ("POST /api/ddis" drugs=[...]").

**Comment by laurmurclar** [comment]
Think we should ask him what the desired behaviour is here before we make changes. Doesn't seem particularly hard to change anyway

**Comment by 22a** [comment]
I think that at the very least, if we keep the system as is, the pml controller is very badly named as it deals with much more than just pml

**Comment by c-brenn** [comment]
Yeah, this is more of a code clarity thing than a real issue - and could be changed without any change to the behaviour the user sees.

My concern is that requests to `/api/pml` do too much atm - and will probably lead to mess in app.js. There are a bunch of interactions to account for.

e.g.  if the pml is fine, but there is some asclepius error - what should the status code be? We probably still want to present the drugs found to the user, but show some error in the ddi panel. 

Chaining a request to `/api/pml` then `/api/ddis` would allow the errors etc to be handled separately

**Comment by laurmurclar** [comment]
Sounds like a good solution to me. I have a lot to do with my FYP today so if I get round to this, it won't be until this evening.

**Comment by c-brenn** [comment]
see #102 - there will now probably be a middle step. Turning english drugs from `/api/pml` into dinto uris for `/api/ddis`
