### ISSUE TITLE
Panacea PML Controller breaks when given valid pml with no drugs

### ISSUE THREAD

**Issue by 22a** [tom-and-the-toothfairies/pathways#98]
The pml controller breaks when given a valid pml file with no drugs( such as the `no_drugs.pml` file in the fixtures directory ) as it sends an empty list to asclepius and matches on the response being {:ok, _} but asclepius will return an error if there aren't at least two drugs present.

<img width="1007" alt="screen shot 2017-03-06 at 20 14 57" src="https://cloud.githubusercontent.com/assets/7144173/23627776/fb8a5418-02a9-11e7-8454-b3f6d4d6f8e1.png">

This controller logic is probably also broken for files with only one identifiable drug, but I haven't tested that.

**Comment by c-brenn** [comment]
When fewer than 2 drugs are found in the doc, we shouldn't query asclepius.

Probably related to #88 - PmlController really should have nothing to do with DDIs
